# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '$(Build.SourcesDirectory)/Plonks.Auth.Test/'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker hub'
        repository: 'jorisk63/plonks'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/Plonks.Auth/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(tag)