# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: SonarCloudPrepare@1
      displayName: Sonar Cloud Prep
      inputs:
        SonarCloud: 'Sonar.Plonks.Auth'
        organization: '409968'
        scannerMode: 'MSBuild'
        projectKey: '409968_Plonks'
        projectName: 'Plonks'
    - task: DotNetCoreCLI@2
      displayName: Build project
      inputs:
        command: 'build'
        projects: '**/Plonks.Auth.Test/*.csproj'
    - task: SonarCloudAnalyze@1
      displayName: Sonar Cloud analysis
    - task: DotNetCoreCLI@2
      displayName: Run tests
      inputs:
        command: 'test'
        projects: '**/Plonks.Auth.Test/*.csproj'
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    - task: PublishTestResults@2
      displayName: Publish test results
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker hub'
        repository: 'jorisk63/plonks'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/Plonks.Auth/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          plonks.auth