apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plonks-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
    - secretName: {{ printf "%s-tls" .Values.hosts.frontend | replace "." "-"}}
      hosts:
        - {{ .Values.hosts.frontend }}
    - secretName: {{ printf "%s-tls" .Values.hosts.gateway | replace "." "-"}}
      hosts:
        - {{ .Values.hosts.gateway }}
  rules:
  - host: {{ .Values.hosts.frontend }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: plonks-{{ .Values.frontend.name }}
            port:
              number: 80
  - host: {{ .Values.hosts.gateway }}
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: plonks-gateway
              port:
                number: 80