apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key
    server: https://acme-v02.api.letsencrypt.org/directory 
    solvers:
      - http01:
          ingress:
            class: nginx