---
apiVersion: v1
kind: Service
metadata:
  name: plonks-boards
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: plonks-boards

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plonks-boards
spec:
  selector:
    matchLabels:
      app: plonks-boards
  replicas: 3
  template:
    metadata:
      labels:
        app: plonks-boards
    spec:
      containers:
      - name: plonks-boards
        image: jorisk63/plonks:plonks.boards
        ports:
        - containerPort: 80