---
apiVersion: v1
kind: Service
metadata:
  name: plonks-auth
  namespace: backend
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: plonks-auth

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plonks-auth
  namespace: backend
spec:
  selector:
    matchLabels:
      app: plonks-auth
  replicas: 3
  template:
    metadata:
      labels:
        app: plonks-auth
    spec:
      containers:
      - name: plonks-auth
        image: jorisk63/plonks:plonks.auth
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
        - name: "PLONKS_ConnectionStrings__DB"
          valueFrom:
            secretKeyRef:
              name: auth-database
              key: ConnectionString
        - name: "PLONKS_ConnectionStrings__ServiceBus"
          valueFrom:
            secretKeyRef:
              name: azure-bus
              key: ConnectionString
        - name: "PLONKS_JWT__Secret"
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: Secret
