---
apiVersion: v1
kind: Service
metadata:
  name: plonks-cards
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: plonks-cards

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plonks-cards
spec:
  selector:
    matchLabels:
      app: plonks-cards
  replicas: 3
  template:
    metadata:
      labels:
        app: plonks-cards
    spec:
      containers:
      - name: plonks-cards
        image: jorisk63/plonks:plonks.cards
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
        - name: "ConnectionStrings__DB"
          valueFrom:
            secretKeyRef:
              name: cards-database
              key: ConnectionString
        - name: "ConnectionStrings__ServiceBus"
          valueFrom:
            secretKeyRef:
              name: azure-bus
              key: ConnectionString
        - name: "JWT__Secret"
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: Secret