---
apiVersion: v1
kind: Service
metadata:
  name: plonks-frontend
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: plonks-frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plonks-frontend
spec:
  selector:
    matchLabels:
      app: plonks-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: plonks-frontend
    spec:
      containers:
      - name: plonks-frontend
        image: jorisk63/plonks:frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80