---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-plonks
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-nginx

spec:
  tls:
    - secretName: plonks-nl-tls
      hosts:
        - plonks.nl
    - secretName: api-plonks-nl-tls
      hosts:
        - api.plonks.nl
  rules:
  - host: plonks.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plonks-frontend
            port:
              number: 80
  - host: api.plonks.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plonks-gateway
            port:
              number: 5000