---
apiVersion: v1
kind: Service
metadata:
  name: plonks-lists
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: plonks-lists

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plonks-lists
spec:
  selector:
    matchLabels:
      app: plonks-lists
  replicas: 3
  template:
    metadata:
      labels:
        app: plonks-lists
    spec:
      containers:
      - name: plonks-lists
        image: jorisk63/plonks:plonks.lists
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
        - name: "ConnectionStrings__DB"
          valueFrom:
            secretKeyRef:
              name: lists-database
              key: ConnectionString
        - name: "ConnectionStrings__ServiceBus"
          valueFrom:
            secretKeyRef:
              name: azure-bus
              key: ConnectionString
        - name: "JWT__Secret"
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: Secret
        - name: "JWT__Issuer"
          value: "https://api.plonks.nl"
        - name: "JWT__Audience"
          value: "https://plonks.nl"
