replicaCount: 1

hosts:
  frontend: plonks.nl
  gateway: api.plonks.nl

frontend:
  name: frontend
  image: jorisk63/plonks:plonks

letsencrypt:
  email: joris.kamminga@gmail.com

microservices:
  - name: auth
    image: jorisk63/plonks:plonks.auth

  - name: boards
    image: jorisk63/plonks:plonks.boards

  - name: lists
    image: jorisk63/plonks:plonks.lists

  - name: cards
    image: jorisk63/plonks:plonks.cards
    
  - name: gateway
    image: jorisk63/plonks:plonks.gateway
