{{- range $index, $microservice := .Values.microservices}}
# ---
apiVersion: v1
kind: Service
metadata:
  name: plonks-{{ $microservice.name }}
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: plonks-{{ $microservice.name }}
{{- end }}